#!/usr/bin/env python3
"""mixed_image_asset_pipeline_smoke.py

Stdlib-only, tempdir-only acceptance smoke for the **mixed image-asset
lane** through ``scripts/run_mock_image_pipeline.py``. Constructs its
own synthetic bundle under a single ``tempfile.TemporaryDirectory()``
containing TWO cover slides — one referencing a ``d_one_local`` image
(mock-generated bytes via the local D-One stub chain) AND one
referencing a ``local_asset`` image (caller-supplied PNG bytes staged
through ``<bundle>/source_assets/``) — drives the runner end-to-end,
and asserts the documented happy-path invariants. Then runs four
fail-closed probes (missing ``source_assets``, wrong ``local_asset``
magic bytes, ``local_asset`` id leaking into ``d_one_spec``, and a
``d_one_local`` / ``local_asset`` ``local_path`` collision) each in its
own tempdir; each must exit non-zero AND leave no ``.pptx`` at the
nominated ``--output`` path.

MOCK / STUB ONLY — NOT real D-One integration. Nothing in this script
calls D-One, MCP, Qoder, a public network, telemetry, any model API,
an image search, a browser, or any external service. The PNG bytes
inlined here (the local_asset payload) and the synthetic PNG produced
by the d_one_local lane are both minimal magic-byte-valid local
payloads; neither is a photographically meaningful image. Real D-One
remains UNVERIFIED.

Positive-chain post-conditions:

  * ``scripts/run_mock_image_pipeline.py`` returns rc=0 against the
    bundle.
  * The produced ``--output`` ``.pptx`` exists as a regular non-symlink
    non-empty file.
  * ``scripts/validate_pptx_contract.py --pptx <out>
    --expected-slide-count 2`` returns rc=0 and emits ``[PASS]`` for
    every ``minimal_evidence.*`` gate the goal pins.
  * ``<report-dir>/inventory.json`` exists, ``ok == True``,
    ``findings == []``, ``slide_count == 2``, and ``media_parts``
    holds AT LEAST TWO internal ``ppt/media/*`` entries whose
    extensions are in ``{.png, .jpg, .jpeg}``.
  * No relationship inside the produced PPTX carries an external
    ``TargetMode``, a URI scheme, ``file://``, ``data:`` scheme, or any
    other scheme prefix (smoke-owned zipfile walk against every
    ``.rels`` part, defense-in-depth alongside the inventory's
    ``relationships.external`` / ``relationships.file_uri`` finding
    codes).
  * The caller-staged ``local_asset`` PNG sha256 appears in
    ``inventory.media_parts[].sha256`` (proves the local_asset lane
    landed byte-identical inside the package, not a copy that was
    re-encoded / metadata-stamped on the way through).
  * The generated mock D-One media sha256 is byte-distinct from the
    local_asset sha256 (proves the two lanes carry independent bytes
    end-to-end, not a collapse where one lane's bytes overwrote the
    other).
  * ``<report-dir>/mock_d_one_adapter_plan.json`` exists, parses as
    JSON, and its ``requests[]`` set is EXACTLY the d_one_local id —
    the local_asset id MUST NOT appear (the sidecar is the audit
    surface for what the mock D-One adapter generated; a local_asset
    id leaking into the sidecar would falsely claim the caller-staged
    bytes were a generated artifact).

Fail-closed probes (each runs in its own tempdir; each must exit
non-zero AND leave no PPTX at the nominated ``--output``):

  P1   missing source_assets — bundle declares a local_asset entry but
       ships no ``<bundle>/source_assets/`` AND no
       ``--source-assets-dir`` flag was passed; the runner refuses at
       its own boundary before any subprocess fires.

  P2   wrong local_asset magic bytes — bundle ships
       ``<bundle>/source_assets/<local_path>`` whose first bytes do
       NOT match the PNG signature; the runner's
       ``_stage_local_assets`` magic-byte gate fires.

  P3   local_asset id leaks into d_one_spec — bundle's
       ``d_one_spec.json`` lists the local_asset manifest id as a
       request; the runner's ``_check_d_one_spec_covers_generated``
       leaked-local-asset gate fires.

  P4   d_one_local / local_asset local_path collision — bundle's
       ``image_manifest_spec.json`` has a d_one_local entry AND a
       local_asset entry that share the same ``local_path``; the
       runner's ``_check_local_path_collision`` gate fires.

Snapshot check: every scenario runs under
``tempfile.TemporaryDirectory()`` with ``TMPDIR=/tmp``. Before the
first scenario the smoke snapshots every committed top-level entry
under ``REPO_ROOT`` (regular files hashed by bytes, directories walked
recursively, symlinks recorded by readlink target). After the last
scenario the snapshot must match byte-for-byte — proves no artifact
(``.pptx`` / inventory / sidecar / report / ``__pycache__`` / package
zip / temp residue) lands under any committed surface.

Stdlib only. NETWORK-FREE. NO real D-One. NO MCP. NO Qoder. NO model
API. NO image search. NO telemetry.
"""
from __future__ import annotations

import sys

# Refuse to write `.pyc` files for any module imported by this script.
# The snapshot check below baselines REPO_ROOT/scripts/ at main() start;
# without this gate, a first-party import below could silently land
# scripts/__pycache__/<module>.cpython-*.pyc before the snapshot fires,
# and the gate would miss the write entirely. Must come BEFORE any
# first-party import; the interpreter checks the flag at bytecode-write
# time. ``PYTHONDONTWRITEBYTECODE=1`` in the env achieves the same
# thing for callers that remember it; the in-script flip closes the
# hole unconditionally.
sys.dont_write_bytecode = True

import argparse  # noqa: E402
import hashlib  # noqa: E402
import json  # noqa: E402
import os  # noqa: E402
import re  # noqa: E402
import subprocess  # noqa: E402
import tempfile  # noqa: E402
import zipfile  # noqa: E402
from dataclasses import dataclass  # noqa: E402
from pathlib import Path  # noqa: E402
from xml.etree import ElementTree as ET  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = REPO_ROOT / "scripts"
TEMPLATE_ROOT = REPO_ROOT / "templates" / "layouts"

RUN_MOCK_IMAGE_PIPELINE = SCRIPTS_DIR / "run_mock_image_pipeline.py"
VALIDATE_PPTX_CONTRACT = SCRIPTS_DIR / "validate_pptx_contract.py"

# Must match scripts/inspect_pptx_inventory.py::EVIDENCE_BASIS verbatim.
EXPECTED_EVIDENCE_BASIS = (
    "OOXML structure only; not proof of full PowerPoint editability"
)

# Filename the runner writes the audit sidecar under, inside --report-dir.
SIDECAR_FILENAME = "mock_d_one_adapter_plan.json"

# OOXML namespace for the Relationships parts the smoke walks.
_NS_REL = "http://schemas.openxmlformats.org/package/2006/relationships"

# Any string with a leading RFC-3986 scheme followed by ':' is treated
# as an external Target. Internal package targets carry no scheme.
_URI_SCHEME_PREFIX = re.compile(r"^[A-Za-z][A-Za-z0-9+.\-]*:")

# Embed surface scripts/export_pptx.py supports today; mirrors
# scripts/run_mock_image_pipeline._EMBEDDABLE_MEDIA_EXTS exactly.
_EMBEDDABLE_MEDIA_EXTS: tuple[str, ...] = (".png", ".jpg", ".jpeg")

# Caller-supplied local_asset PNG payload. Must pass the PNG magic-byte
# gate (`\x89PNG\r\n\x1a\n` prefix). The trailing pad differs from the
# d_one_local mock payload so sha256(local_asset) != sha256(d_one_local)
# and the smoke can prove the two lanes carry independent bytes.
_LOCAL_ASSET_PNG_BYTES: bytes = (
    b"\x89PNG\r\n\x1a\n"
    + b"\x00\x00\x00\rIHDR"
    + b"\xa5" * 64
)
_LOCAL_ASSET_PNG_SHA256 = hashlib.sha256(_LOCAL_ASSET_PNG_BYTES).hexdigest()

# Synthetic identifiers — the smoke owns them so the runner's audit
# sidecar can be cross-checked against the smoke's own knowledge of
# which ids belong to which lane.
SYNTHETIC_SOURCE_ID = "synthetic_mixed_image_smoke_source"
D_ONE_IMAGE_ID = "mixed_d_one_accent"
LOCAL_ASSET_IMAGE_ID = "mixed_local_asset_accent"
D_ONE_LOCAL_PATH = "media/mixed_d_one_accent.png"
LOCAL_ASSET_LOCAL_PATH = "media/mixed_local_asset_accent.png"
D_ONE_SLIDE_TITLE = "Mixed Lane D-One Cover"
LOCAL_ASSET_SLIDE_TITLE = "Mixed Lane Local Asset Cover"
SYNTHETIC_AUDIENCE = "Internal mixed-lane reviewers"
SYNTHETIC_OBJECTIVE = (
    "Exercise the mixed d_one_local + local_asset image-asset lane "
    "end-to-end through run_mock_image_pipeline."
)

REAL_D_ONE_STATUS = (
    "UNVERIFIED — real D-One is NOT called by this smoke. The "
    "local_asset PNG payload inlined in this script and the "
    "d_one_local synthetic PNG produced by the mock chain are both "
    "minimal magic-byte-valid local payloads; nothing here calls "
    "D-One, MCP, Qoder, a public network, telemetry, any model API, "
    "an image search, a browser, or any external service."
)


# ---------------------------------------------------------------------------
# Snapshot helpers — prove the smoke writes nothing under REPO_ROOT.
# Mirrors the type-tagged shape ``core_editable_ppt_acceptance``
# already uses so a planted symlink / FIFO surfaces in the diff rather
# than being silently skipped.
# ---------------------------------------------------------------------------


_COMMITTED_TOP_LEVEL: tuple[str, ...] = (
    ".gitignore",
    "AGENTS.md",
    "CLAUDE.md",
    "README.md",
    "SECURITY.md",
    "SKILL.md",
    "examples",
    "references",
    "schemas",
    "scripts",
    "templates",
)


def _record_snapshot_entry(
    p: Path, key: str, out: dict[str, tuple[str, bytes]],
) -> None:
    if p.is_symlink():
        try:
            tgt = os.readlink(p).encode("utf-8", "surrogateescape")
        except OSError:
            tgt = b"<unreadable-symlink-target>"
        out[key] = ("symlink", tgt)
        return
    if p.is_file():
        out[key] = ("file", p.read_bytes())
        return
    if p.is_dir():
        out[key] = ("dir", b"")
        return
    if p.exists():
        out[key] = ("other", b"")


def _snapshot_committed_tree() -> dict[str, tuple[str, bytes]]:
    out: dict[str, tuple[str, bytes]] = {}
    for name in _COMMITTED_TOP_LEVEL:
        p = REPO_ROOT / name
        _record_snapshot_entry(p, name, out)
        if not p.is_symlink() and p.is_dir():
            for child in sorted(p.rglob("*")):
                _record_snapshot_entry(
                    child, str(child.relative_to(REPO_ROOT)), out,
                )
    return out


def _check_repo_unchanged(
    before: dict[str, tuple[str, bytes]],
) -> int:
    after = _snapshot_committed_tree()
    if before == after:
        return 0
    changed = sorted(
        k for k in set(before) | set(after)
        if before.get(k) != after.get(k)
    )
    print(
        f"FAIL: committed tree under REPO_ROOT was mutated by the "
        f"mixed-image-asset pipeline smoke (changed: {changed!r}).",
        file=sys.stderr,
    )
    return 1


# ---------------------------------------------------------------------------
# Subprocess runner.
# ---------------------------------------------------------------------------


@dataclass
class ToolOutcome:
    name: str
    cmd: list[str]
    rc: int
    stdout: str
    stderr: str

    @property
    def ok(self) -> bool:
        return self.rc == 0

    @property
    def combined(self) -> str:
        return (self.stdout or "") + (self.stderr or "")


def _run(name: str, cmd: list[str]) -> ToolOutcome:
    env = {**os.environ, "PYTHONDONTWRITEBYTECODE": "1"}
    proc = subprocess.run(
        cmd, cwd=REPO_ROOT, capture_output=True, text=True, env=env,
    )
    return ToolOutcome(
        name=name, cmd=cmd, rc=proc.returncode,
        stdout=proc.stdout, stderr=proc.stderr,
    )


def _print_outcome(o: ToolOutcome) -> None:
    print(f"  [{'PASS' if o.ok else 'FAIL'}] {o.name} (rc={o.rc})")
    if not o.ok:
        for stream_name, body in (("stdout", o.stdout), ("stderr", o.stderr)):
            tail = (body or "").splitlines()[-15:]
            if tail:
                print(f"    {stream_name} tail:")
                for line in tail:
                    print(f"      {line}")


# ---------------------------------------------------------------------------
# Fixture writers — author the synthetic mixed-lane bundle under a
# caller-owned tempdir. The bundle layout mirrors
# scripts/run_mock_image_pipeline._resolve_bundle exactly so the
# happy-path probe drives the same code path real callers exercise.
# ---------------------------------------------------------------------------


def _write_json(path: Path, body: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(body, indent=2, sort_keys=True) + "\n")


def _source_md() -> str:
    return (
        "# Mixed-Lane Synthetic Source\n\n"
        "Synthetic source body authored by mixed_image_asset_pipeline_"
        "smoke.py. No image bytes are extracted from this body; "
        "the d_one_local lane produces its own synthetic PNG and the "
        "local_asset lane reads pre-staged bytes from "
        "<bundle>/source_assets/.\n"
    )


def _brief_body() -> dict:
    return {
        "title": D_ONE_SLIDE_TITLE,
        "audience": SYNTHETIC_AUDIENCE,
        "objective": SYNTHETIC_OBJECTIVE,
        "source_id": SYNTHETIC_SOURCE_ID,
    }


def _plan_spec_body() -> dict:
    return {
        "template": "business_review",
        "planning": {
            "planned_slide_count": 2,
            "rationale": (
                "Two cover slides covering both image-source lanes: "
                "slide 1 carries the d_one_local generated accent, "
                "slide 2 carries the caller-supplied local_asset "
                "accent."
            ),
        },
        "sections": [
            {
                "id": "generated", "title": "Generated",
                "summary": "Cover with mock D-One generated accent.",
                "slide_indices": [1],
            },
            {
                "id": "local", "title": "Local",
                "summary": "Cover with caller-supplied local accent.",
                "slide_indices": [2],
            },
        ],
        "slides": [
            {
                "index": 1, "layout": "cover",
                "title": D_ONE_SLIDE_TITLE,
                "section_id": "generated",
                "summary": (
                    "Cover with a mock D-One generated PNG accent."
                ),
                "density": "low",
                "source_refs": [SYNTHETIC_SOURCE_ID],
            },
            {
                "index": 2, "layout": "cover",
                "title": LOCAL_ASSET_SLIDE_TITLE,
                "section_id": "local",
                "summary": (
                    "Cover with a caller-supplied local_asset PNG."
                ),
                "density": "low",
                "source_refs": [SYNTHETIC_SOURCE_ID],
            },
        ],
    }


def _design_system_body() -> dict:
    return {
        "palette": {
            "primary": "#264653",
            "secondary": "#2A9D8F",
            "accent": "#E9C46A",
            "background": "#FFFFFF",
            "text": "#1A1A1A",
        },
        "typography": {
            "heading": {
                "font_family":
                    "Calibri, Helvetica Neue, Arial, sans-serif",
                "size_pt": 28,
            },
            "body": {
                "font_family":
                    "Calibri, Helvetica Neue, Arial, sans-serif",
                "size_pt": 14,
            },
        },
        "grid": {"width_px": 1920, "height_px": 1080, "margin_px": 64},
    }


def _slide_cover_body(*, index: int, title: str, image_id: str) -> dict:
    return {
        "index": index, "layout": "cover", "title": title,
        "subtitle": "Mixed-lane synthetic cover",
        "blocks": [
            {"id": "title", "kind": "text", "content": title},
            {"id": "subtitle", "kind": "text",
             "content": "Mixed-lane synthetic cover"},
            {"id": "presenter", "kind": "text",
             "content": "Synthetic Reviewer"},
            {"id": "date", "kind": "text",
             "content": "Synthetic window"},
            {"id": "accent", "kind": "image_ref", "content": image_id},
        ],
        "image_refs": [image_id],
        "notes": "Synthetic.",
    }


def _image_manifest_spec_body() -> dict:
    return {
        "images": [
            {
                "id": D_ONE_IMAGE_ID,
                "local_path": D_ONE_LOCAL_PATH,
                "source": "d_one_local",
                "alt_text": (
                    "Mock D-One generated accent (mixed-lane smoke)."
                ),
                "intended_use": "spot illustration",
            },
            {
                "id": LOCAL_ASSET_IMAGE_ID,
                "local_path": LOCAL_ASSET_LOCAL_PATH,
                "source": "local_asset",
                "alt_text": (
                    "Caller-supplied PNG (mixed-lane smoke)."
                ),
                "intended_use": "spot illustration",
            },
        ],
    }


def _d_one_spec_body() -> dict:
    # Only the d_one_local id; the local_asset id MUST NOT appear here.
    # No taxonomy fields so --descriptor-vocabulary is not required.
    return {
        "requests": [
            {
                "id": D_ONE_IMAGE_ID,
                "prompt": (
                    "abstract calm geometric accent, no text, no logo"
                ),
                "intended_use": "spot illustration",
                "width_px": 320, "height_px": 320,
            },
        ],
    }


def _materialize_bundle(
    td: Path,
    *,
    with_source_assets: bool = True,
    local_asset_payload: bytes = _LOCAL_ASSET_PNG_BYTES,
    image_manifest_spec_overrides: dict | None = None,
    d_one_spec_overrides: dict | None = None,
    local_asset_dst_local_path: str | None = None,
) -> dict:
    """Write the synthetic mixed-lane bundle under ``<td>/bundle/`` and
    return a dict of resolved paths.

    ``with_source_assets`` controls whether ``<bundle>/source_assets/``
    is created (False is the P1 missing-source_assets probe).
    ``local_asset_payload`` lets a probe inject magic-byte-invalid
    bytes (P2). ``image_manifest_spec_overrides`` lets P4 inject a
    local_path collision; ``d_one_spec_overrides`` lets P3 leak the
    local_asset id into the d_one_spec.
    ``local_asset_dst_local_path`` lets the staging copy land at a
    different name than the manifest entry's local_path (used by P2
    to ensure the magic-byte gate fires before any extension swap)."""
    bundle = td / "bundle"
    bundle.mkdir(parents=True)
    source = bundle / "source.md"
    source.write_text(_source_md(), encoding="utf-8")

    _write_json(bundle / "brief.json", _brief_body())
    _write_json(bundle / "plan_spec.json", _plan_spec_body())
    _write_json(bundle / "design_system_spec.json", _design_system_body())

    slide_specs = bundle / "slide_specs"
    slide_specs.mkdir()
    _write_json(
        slide_specs / "01_cover.json",
        _slide_cover_body(
            index=1, title=D_ONE_SLIDE_TITLE, image_id=D_ONE_IMAGE_ID,
        ),
    )
    _write_json(
        slide_specs / "02_cover.json",
        _slide_cover_body(
            index=2, title=LOCAL_ASSET_SLIDE_TITLE,
            image_id=LOCAL_ASSET_IMAGE_ID,
        ),
    )

    manifest_body = _image_manifest_spec_body()
    if image_manifest_spec_overrides is not None:
        manifest_body = image_manifest_spec_overrides
    _write_json(bundle / "image_manifest_spec.json", manifest_body)

    d_one_body = _d_one_spec_body()
    if d_one_spec_overrides is not None:
        d_one_body = d_one_spec_overrides
    _write_json(bundle / "d_one_spec.json", d_one_body)

    if with_source_assets:
        source_assets = bundle / "source_assets"
        source_assets.mkdir()
        dst_local = (
            local_asset_dst_local_path
            if local_asset_dst_local_path is not None
            else LOCAL_ASSET_LOCAL_PATH
        )
        leaf = source_assets / dst_local
        leaf.parent.mkdir(parents=True, exist_ok=True)
        leaf.write_bytes(local_asset_payload)

    return {
        "bundle": bundle,
        "source": source,
    }


def _runner_args(
    *, bundle_dir: Path, workspace: Path, output: Path,
    report_dir: Path | None = None,
) -> list[str]:
    args = [
        sys.executable, str(RUN_MOCK_IMAGE_PIPELINE),
        "--bundle", str(bundle_dir),
        "--workspace", str(workspace),
        "--output", str(output),
        "--allow-synthetic-bytes",
        "--template-root", str(TEMPLATE_ROOT),
    ]
    if report_dir is not None:
        args += ["--report-dir", str(report_dir)]
    return args


# ---------------------------------------------------------------------------
# Positive-proof assertions.
# ---------------------------------------------------------------------------


@dataclass
class Assertion:
    name: str
    ok: bool
    detail: str = ""


def _list_pptx_media_parts(pptx: Path) -> tuple[list[str], Exception | None]:
    try:
        zf = zipfile.ZipFile(pptx, "r")
    except (zipfile.BadZipFile, OSError) as exc:
        return [], exc
    try:
        names = zf.namelist()
    finally:
        zf.close()
    return sorted(
        n for n in names
        if n.startswith("ppt/media/")
        and Path(n).suffix.lower() in _EMBEDDABLE_MEDIA_EXTS
    ), None


def _pptx_media_shas(pptx: Path) -> tuple[dict[str, str], Exception | None]:
    """Return (part -> sha256) for every embeddable ppt/media/* part."""
    media, err = _list_pptx_media_parts(pptx)
    if err is not None:
        return {}, err
    out: dict[str, str] = {}
    try:
        zf = zipfile.ZipFile(pptx, "r")
    except (zipfile.BadZipFile, OSError) as exc:
        return {}, exc
    try:
        for n in media:
            try:
                payload = zf.read(n)
            except (KeyError, OSError):
                continue
            out[n] = hashlib.sha256(payload).hexdigest()
    finally:
        zf.close()
    return out, None


def _assert_pptx_relationships_internal_only(
    pptx: Path,
) -> list[Assertion]:
    results: list[Assertion] = []
    try:
        zf = zipfile.ZipFile(pptx, "r")
    except (zipfile.BadZipFile, OSError) as exc:
        results.append(Assertion(
            "PPTX opens as ZIP for relationships walk",
            False, f"{type(exc).__name__}: {exc}",
        ))
        return results
    try:
        external: list[str] = []
        rel_tag = f"{{{_NS_REL}}}Relationship"
        for n in zf.namelist():
            if not n.endswith(".rels"):
                continue
            try:
                root = ET.fromstring(zf.read(n))
            except (KeyError, OSError, ET.ParseError) as exc:
                external.append(
                    f"{n}: cannot parse: {type(exc).__name__}: {exc}"
                )
                continue
            for el in root:
                if el.tag != rel_tag:
                    continue
                target = el.attrib.get("Target", "")
                mode = el.attrib.get("TargetMode", "")
                if mode and mode != "Internal":
                    external.append(
                        f"{n}: id={el.attrib.get('Id')!r} "
                        f"TargetMode={mode!r} Target={target!r}"
                    )
                    continue
                if _URI_SCHEME_PREFIX.match(target):
                    external.append(
                        f"{n}: id={el.attrib.get('Id')!r} "
                        f"Target={target!r} (URI scheme)"
                    )
        results.append(Assertion(
            "PPTX has no external / file:// / data: / URI-scheme "
            "relationships",
            not external,
            "; ".join(external),
        ))
    finally:
        zf.close()
    return results


def _assert_contract_minimal_evidence_pass(
    outcome: ToolOutcome,
) -> list[Assertion]:
    results: list[Assertion] = []
    out = outcome.combined
    for gate in (
        "minimal_evidence.editable_text",
        "minimal_evidence.not_all_image_slide",
        "minimal_evidence.no_blank_slide",
        "minimal_evidence.every_slide_has_native_shape",
    ):
        marker = f"[PASS] {gate}"
        results.append(Assertion(
            f"validate_pptx_contract emits [PASS] for {gate}",
            marker in out,
            f"marker {marker!r} not in validator output; "
            f"tail={out.splitlines()[-15:]!r}",
        ))
    return results


def _assert_inventory_contract(
    *, inventory_path: Path, local_asset_sha: str,
) -> tuple[list[Assertion], set[str]]:
    """Open inventory.json and assert the documented gates plus the
    mixed-lane post-conditions. Returns (assertions, media_shas) so the
    caller can compare media_shas against the local_asset sha + the
    independently observed generated-media sha for the lane-distinctness
    check."""
    results: list[Assertion] = []
    media_shas: set[str] = set()
    inv_is_file = (
        inventory_path.is_file() and not inventory_path.is_symlink()
    )
    results.append(Assertion(
        "inventory.json exists as a regular non-symlink file",
        inv_is_file, f"path={inventory_path}",
    ))
    if not inv_is_file:
        return results, media_shas
    try:
        inv = json.loads(inventory_path.read_text())
    except (json.JSONDecodeError, OSError) as exc:
        results.append(Assertion(
            "inventory.json parses as JSON",
            False, f"{type(exc).__name__}: {exc}",
        ))
        return results, media_shas
    results.append(Assertion(
        "inventory.ok is True",
        inv.get("ok") is True, f"got {inv.get('ok')!r}",
    ))
    results.append(Assertion(
        "inventory.findings is []",
        inv.get("findings") == [], f"got {inv.get('findings')!r}",
    ))
    results.append(Assertion(
        "inventory.slide_count == 2",
        inv.get("slide_count") == 2, f"got {inv.get('slide_count')!r}",
    ))
    results.append(Assertion(
        "inventory.evidence_basis matches the documented line",
        inv.get("evidence_basis") == EXPECTED_EVIDENCE_BASIS,
        f"got {inv.get('evidence_basis')!r}",
    ))
    mp = inv.get("media_parts")
    is_list = isinstance(mp, list)
    if is_list:
        for entry in mp:
            if not isinstance(entry, dict):
                continue
            sha = entry.get("sha256")
            part = entry.get("part")
            ext = entry.get("extension")
            if (
                isinstance(sha, str)
                and isinstance(part, str)
                and part.startswith("ppt/media/")
                and isinstance(ext, str)
                and "." + ext.lower() in _EMBEDDABLE_MEDIA_EXTS
            ):
                media_shas.add(sha)
    embeddable_count = len(media_shas)
    results.append(Assertion(
        "inventory.media_parts has >= 2 internal "
        "PNG/JPG/JPEG entries",
        is_list and embeddable_count >= 2,
        f"embeddable_count={embeddable_count}, media_parts={mp!r}",
    ))
    results.append(Assertion(
        "local_asset sha256 appears in inventory.media_parts[].sha256",
        local_asset_sha in media_shas,
        f"local_asset_sha={local_asset_sha!r}, "
        f"media_shas={sorted(media_shas)!r}",
    ))
    return results, media_shas


def _assert_sidecar_covers_only_d_one(
    sidecar_path: Path,
) -> list[Assertion]:
    results: list[Assertion] = []
    is_file = sidecar_path.is_file() and not sidecar_path.is_symlink()
    results.append(Assertion(
        f"sidecar {SIDECAR_FILENAME} exists as a regular non-symlink "
        f"file under --report-dir",
        is_file, f"path={sidecar_path}",
    ))
    if not is_file:
        return results
    try:
        body = json.loads(sidecar_path.read_text())
    except (json.JSONDecodeError, OSError) as exc:
        results.append(Assertion(
            f"sidecar {SIDECAR_FILENAME} parses as JSON",
            False, f"{type(exc).__name__}: {exc}",
        ))
        return results
    reqs = body.get("requests")
    ids: list[str] = []
    if isinstance(reqs, list):
        for r in reqs:
            if isinstance(r, dict) and isinstance(r.get("id"), str):
                ids.append(r["id"])
    results.append(Assertion(
        "sidecar requests[].id == [D_ONE_IMAGE_ID] exactly "
        "(d_one_local lane only)",
        ids == [D_ONE_IMAGE_ID],
        f"got requests ids={ids!r}",
    ))
    results.append(Assertion(
        "sidecar requests[] does NOT carry the local_asset id "
        "(caller-staged bytes are not a generated artifact)",
        LOCAL_ASSET_IMAGE_ID not in ids,
        f"got requests ids={ids!r}",
    ))
    return results


# ---------------------------------------------------------------------------
# Positive chain.
# ---------------------------------------------------------------------------


def _run_positive_chain(td: Path) -> tuple[bool, list[Assertion]]:
    print("--- positive proof (mixed lane: d_one_local + local_asset) ---")
    workspace = td / "workspace"
    output = td / "mixed.pptx"
    report_dir = td / "report"
    bundle = _materialize_bundle(td)
    print(f"  bundle:       {bundle['bundle']}")
    print(f"  workspace:    {workspace}")
    print(f"  pptx output:  {output}")
    print(f"  report dir:   {report_dir}")
    print(
        f"  local_asset sha256={_LOCAL_ASSET_PNG_SHA256[:16]}... "
        f"({len(_LOCAL_ASSET_PNG_BYTES)} bytes)"
    )

    runner = _run(
        "run_mock_image_pipeline (mixed-lane bundle)",
        _runner_args(
            bundle_dir=bundle["bundle"], workspace=workspace,
            output=output, report_dir=report_dir,
        ),
    )
    _print_outcome(runner)
    if not runner.ok:
        return False, [Assertion(
            "run_mock_image_pipeline returns rc=0",
            False,
            f"rc={runner.rc}; "
            f"tail={runner.combined.splitlines()[-20:]!r}",
        )]

    assertions: list[Assertion] = []

    pptx_is_file = output.is_file() and not output.is_symlink()
    assertions.append(Assertion(
        "final PPTX exists as a regular non-symlink file",
        pptx_is_file, f"path={output}",
    ))
    if pptx_is_file:
        size = output.stat().st_size
        assertions.append(Assertion(
            "final PPTX is non-empty",
            size > 0, f"size={size}",
        ))
        assertions.extend(
            _assert_pptx_relationships_internal_only(output)
        )

    # Contract validator with --expected-slide-count 2.
    contract = _run(
        "validate_pptx_contract --expected-slide-count 2",
        [
            sys.executable, str(VALIDATE_PPTX_CONTRACT),
            "--pptx", str(output),
            "--expected-slide-count", "2",
        ],
    )
    _print_outcome(contract)
    assertions.append(Assertion(
        "validate_pptx_contract --expected-slide-count 2 returns rc=0",
        contract.ok,
        f"rc={contract.rc}; "
        f"tail={contract.combined.splitlines()[-15:]!r}",
    ))
    assertions.extend(_assert_contract_minimal_evidence_pass(contract))

    # Inventory readback. run_mock_image_pipeline writes inventory.json
    # via the downstream orchestrator under --report-dir.
    inv_assertions, inventory_media_shas = _assert_inventory_contract(
        inventory_path=report_dir / "inventory.json",
        local_asset_sha=_LOCAL_ASSET_PNG_SHA256,
    )
    assertions.extend(inv_assertions)

    # Cross-check the inventory media shas against the actual ZIP shas
    # for the generated-media lane-distinctness assertion. The PPTX
    # parses as ZIP; for every embeddable media part we record sha256
    # directly so the d_one_local sha is whichever observed sha is NOT
    # the local_asset sha.
    pptx_shas, pptx_err = _pptx_media_shas(output)
    if pptx_err is not None:
        assertions.append(Assertion(
            "PPTX opens as ZIP for media-sha walk",
            False, f"{type(pptx_err).__name__}: {pptx_err}",
        ))
    else:
        observed = set(pptx_shas.values())
        assertions.append(Assertion(
            "inventory.media_parts sha set covers every observed "
            "ppt/media/* sha (no inventory drift)",
            observed <= inventory_media_shas,
            f"observed={sorted(observed)!r}; "
            f"inventory={sorted(inventory_media_shas)!r}",
        ))
        d_one_shas = observed - {_LOCAL_ASSET_PNG_SHA256}
        assertions.append(Assertion(
            "at least one generated d_one_local media sha is byte-"
            "distinct from the local_asset sha (the two lanes "
            "produce independent bytes end-to-end)",
            bool(d_one_shas),
            f"observed_shas={sorted(observed)!r}; "
            f"local_asset_sha={_LOCAL_ASSET_PNG_SHA256!r}",
        ))

    # Audit sidecar: covers only the d_one_local request id.
    assertions.extend(
        _assert_sidecar_covers_only_d_one(report_dir / SIDECAR_FILENAME)
    )

    ok = all(a.ok for a in assertions)
    return ok, assertions


# ---------------------------------------------------------------------------
# Fail-closed probes.
# ---------------------------------------------------------------------------


@dataclass
class ProbeResult:
    name: str
    ok: bool
    detail: str = ""


def _probe_runner_fails(
    *,
    name: str,
    td: Path,
    bundle_dir: Path,
    expected_substrings: list[str],
) -> ProbeResult:
    """Drive run_mock_image_pipeline against ``bundle_dir`` and assert
    rc != 0 AND no .pptx lands at the nominated --output."""
    workspace = td / "workspace"
    output = td / "should_not_exist.pptx"
    report_dir = td / "report"
    outcome = _run(
        "run_mock_image_pipeline (probe)",
        _runner_args(
            bundle_dir=bundle_dir, workspace=workspace,
            output=output, report_dir=report_dir,
        ),
    )
    diagnostics: list[str] = []
    if outcome.ok:
        diagnostics.append(
            f"rc=0 (expected non-zero); "
            f"tail={outcome.combined.splitlines()[-20:]!r}"
        )
    missing = [s for s in expected_substrings if s not in outcome.combined]
    if missing:
        diagnostics.append(
            f"expected diagnostic substring(s) {missing!r} not found; "
            f"tail={outcome.combined.splitlines()[-20:]!r}"
        )
    if output.exists() or output.is_symlink():
        diagnostics.append(
            f"--output {output} exists after fail-closed run; "
            f"the runner must not leave a stray .pptx on failure"
        )
    return ProbeResult(
        name=name, ok=not diagnostics,
        detail="; ".join(diagnostics),
    )


def _probe_missing_source_assets() -> ProbeResult:
    """P1: bundle declares a local_asset entry but ships no
    <bundle>/source_assets/ AND --source-assets-dir is not passed."""
    with tempfile.TemporaryDirectory(
        prefix="szh_mixed_smoke_p1_",
    ) as raw_td:
        td = Path(raw_td)
        bundle = _materialize_bundle(td, with_source_assets=False)
        return _probe_runner_fails(
            name=(
                "P1: missing source_assets -> runner refuses at "
                "boundary (--source-assets-dir required for "
                "local_asset entries)"
            ),
            td=td,
            bundle_dir=bundle["bundle"],
            expected_substrings=[
                "local_asset", "--source-assets-dir",
            ],
        )


def _probe_wrong_local_asset_magic() -> ProbeResult:
    """P2: bundle ships <bundle>/source_assets/<local_path> whose first
    bytes do NOT match the PNG signature; _stage_local_assets' magic-
    byte gate fires."""
    with tempfile.TemporaryDirectory(
        prefix="szh_mixed_smoke_p2_",
    ) as raw_td:
        td = Path(raw_td)
        bundle = _materialize_bundle(
            td,
            local_asset_payload=(
                # 32 bytes that do NOT start with `\x89PNG\r\n\x1a\n`.
                b"NOT_A_PNG_HEADER_" + b"\x00" * 16
            ),
        )
        return _probe_runner_fails(
            name=(
                "P2: local_asset bytes fail PNG magic-byte gate -> "
                "_stage_local_assets refuses"
            ),
            td=td,
            bundle_dir=bundle["bundle"],
            expected_substrings=[
                "magic bytes", LOCAL_ASSET_LOCAL_PATH,
            ],
        )


def _probe_local_asset_id_in_d_one_spec() -> ProbeResult:
    """P3: bundle's d_one_spec.json lists the local_asset manifest id
    as a request; _check_d_one_spec_covers_generated's leaked-local-
    asset branch fires before any subprocess runs."""
    leaked_spec = {
        "requests": [
            {
                "id": D_ONE_IMAGE_ID,
                "prompt": (
                    "abstract calm geometric accent, no text, no logo"
                ),
                "intended_use": "spot illustration",
                "width_px": 320, "height_px": 320,
            },
            {
                "id": LOCAL_ASSET_IMAGE_ID,  # leaks here.
                "prompt": (
                    "abstract calm geometric accent, no text, no logo"
                ),
                "intended_use": "spot illustration",
                "width_px": 320, "height_px": 320,
            },
        ],
    }
    with tempfile.TemporaryDirectory(
        prefix="szh_mixed_smoke_p3_",
    ) as raw_td:
        td = Path(raw_td)
        bundle = _materialize_bundle(
            td, d_one_spec_overrides=leaked_spec,
        )
        return _probe_runner_fails(
            name=(
                "P3: local_asset id leaks into d_one_spec -> "
                "_check_d_one_spec_covers_generated refuses"
            ),
            td=td,
            bundle_dir=bundle["bundle"],
            expected_substrings=[
                "local_asset", LOCAL_ASSET_IMAGE_ID,
            ],
        )


def _probe_local_path_collision() -> ProbeResult:
    """P4: bundle's image_manifest_spec has a d_one_local entry AND a
    local_asset entry sharing the same local_path; the runner's
    _check_local_path_collision gate fires."""
    shared_path = "media/shared_collision.png"
    collision_manifest = {
        "images": [
            {
                "id": D_ONE_IMAGE_ID,
                "local_path": shared_path,
                "source": "d_one_local",
                "alt_text": "Generated accent (collision probe).",
                "intended_use": "spot illustration",
            },
            {
                "id": LOCAL_ASSET_IMAGE_ID,
                "local_path": shared_path,  # same as the d_one_local entry.
                "source": "local_asset",
                "alt_text": "Caller accent (collision probe).",
                "intended_use": "spot illustration",
            },
        ],
    }
    with tempfile.TemporaryDirectory(
        prefix="szh_mixed_smoke_p4_",
    ) as raw_td:
        td = Path(raw_td)
        bundle = _materialize_bundle(
            td,
            image_manifest_spec_overrides=collision_manifest,
            local_asset_dst_local_path=shared_path,
        )
        # Rewrite the slide_specs so each cover references an existing
        # image_ref (the manifest still declares both ids, just at the
        # same local_path — the lane-collision gate fires before any
        # slide-level check kicks in). Use the canonical local_paths in
        # plan/slides; only the manifest's local_path was perturbed.
        return _probe_runner_fails(
            name=(
                "P4: d_one_local / local_asset local_path collision -> "
                "_check_local_path_collision refuses"
            ),
            td=td,
            bundle_dir=bundle["bundle"],
            expected_substrings=[
                "local_path", "d_one_local", "local_asset",
            ],
        )


# ---------------------------------------------------------------------------
# Self-test entry point.
# ---------------------------------------------------------------------------


def _run_self_test() -> int:
    print(
        "=== mixed image-asset pipeline smoke "
        "(mock chain; real D-One UNVERIFIED) ==="
    )
    if not TEMPLATE_ROOT.is_dir():
        print(
            f"FAIL: template root not found at {TEMPLATE_ROOT}; the "
            f"smoke requires the committed business_review template.",
            file=sys.stderr,
        )
        return 1
    if not RUN_MOCK_IMAGE_PIPELINE.is_file():
        print(
            f"FAIL: scripts/run_mock_image_pipeline.py not found at "
            f"{RUN_MOCK_IMAGE_PIPELINE}",
            file=sys.stderr,
        )
        return 1
    tree_before = _snapshot_committed_tree()

    with tempfile.TemporaryDirectory(
        prefix="szh_mixed_image_asset_pipeline_smoke_",
    ) as raw_td:
        td = Path(raw_td)
        print(f"  tempdir: {td}")
        print()
        positive_ok, positive_results = _run_positive_chain(td)
        print()
        print("--- positive assertions ---")
        fails = 0
        for a in positive_results:
            mark = "PASS" if a.ok else "FAIL"
            suffix = f" -- {a.detail}" if not a.ok and a.detail else ""
            print(f"  [{mark}] {a.name}{suffix}")
            if not a.ok:
                fails += 1
        print()
        if not positive_ok or fails:
            print(
                f"FAIL: positive proof did not hold "
                f"({fails} assertion(s) failed).",
                file=sys.stderr,
            )
            _check_repo_unchanged(tree_before)
            return 1

    print("--- negative probes ---")
    probes: list[ProbeResult] = [
        _probe_missing_source_assets(),
        _probe_wrong_local_asset_magic(),
        _probe_local_asset_id_in_d_one_spec(),
        _probe_local_path_collision(),
    ]
    fails = 0
    for r in probes:
        mark = "PASS" if r.ok else "FAIL"
        suffix = f" -- {r.detail}" if not r.ok and r.detail else ""
        print(f"  [{mark}] {r.name}{suffix}")
        if not r.ok:
            fails += 1

    rc_snapshot = _check_repo_unchanged(tree_before)
    if fails or rc_snapshot != 0:
        print(
            f"\nFAIL: {fails} negative probe(s) did not fire as "
            f"documented; snapshot rc={rc_snapshot}.",
            file=sys.stderr,
        )
        return 1

    print()
    print(
        "OK (self-test): mixed image-asset pipeline smoke passed.\n"
        f"  Real D-One status: {REAL_D_ONE_STATUS}"
    )
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Mixed image-asset pipeline smoke: proves the d_one_local + "
            "local_asset mixed lane flows end-to-end through "
            "scripts/run_mock_image_pipeline.py --bundle into a "
            "validated editable .pptx — two cover slides, two distinct "
            "internal ppt/media/* parts (one per lane), the "
            "local_asset sha256 lands in the inventory media_parts, "
            "the generated d_one_local media sha is byte-distinct from "
            "the local_asset sha, and the runner's audit sidecar "
            "(mock_d_one_adapter_plan.json) covers ONLY the "
            "d_one_local request id. Also runs four fail-closed probes "
            "(missing source_assets, wrong local_asset magic, "
            "local_asset id leaked into d_one_spec, lane local_path "
            "collision); each must exit non-zero AND leave no .pptx "
            "behind. MOCK / STUB only — NOT real D-One integration; "
            "no MCP, no public network, no model API, no image search, "
            "no Qoder, no external service."
        ),
    )
    parser.add_argument(
        "--self-test", action="store_true",
        help=(
            "Run the positive proof end-to-end and every documented "
            "fail-closed probe under tempfile.TemporaryDirectory(). "
            "The smoke has no other mode today; --self-test is "
            "required."
        ),
    )
    args = parser.parse_args(argv)
    if not args.self_test:
        print(
            "FAIL: mixed_image_asset_pipeline_smoke.py requires "
            "--self-test (no production CLI surface exists today).",
            file=sys.stderr,
        )
        return 2
    return _run_self_test()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
