#!/usr/bin/env python3
"""Mock-generated-image -> editable-PPT operator-review-package handoff smoke.

Proves that locally produced mock/generated PNG + JPEG image bytes ride
the same operator review package path that caller-supplied operator
photos already ride:

  1. assemble a temp-only bundle ``<temp>/bundle/`` carrying
     ``images/mock_generated_alpha.png`` + ``images/mock_generated_beta.jpg``
     (the minimum-viable magic-byte-valid PNG / JPEG bytes the operator
     helper's own --self-test uses, byte-distinct so the per-image sha256
     attribution can prove "each mock-generated file embedded" honestly)
     plus a safe ``manifest.json`` that pins per-image slide_title /
     alt_text / intended_use using only non-network / non-credential /
     non-confidential / non-public-hosting / non-real-service wording so
     ``validate_operator_review_package.py``'s string-safety scans pass
     unchanged;
  2. invoke ``scripts/operator_local_images_to_editable_ppt.py --bundle
     <bundle> --out-dir <out>`` and assert ``rc == 0``;
  3. invoke ``scripts/validate_operator_review_package.py --out-dir
     <out>`` and assert ``rc == 0``;
  4. parse ``<out>/summary.json`` and assert ``image_provenance`` ties
     EACH mock-generated filename to a non-empty list of
     ``embedded_media_parts`` (sha256 -> ``ppt/media/*`` part paths) AND
     to a non-empty list of ``embedded_referencing_slides`` that
     contains the row's ``intended_slide_index`` (placement_verified is
     therefore True) — the truth the operator helper writes is the
     truth the validator reads, and both agree the mock-generated bytes
     made it into the deck at the intended slide.

This is a NARROW handoff proof, NOT a new runtime product. The smoke
only drives the existing operator + validator entry points; it does
NOT plan a deck, infer slide content from any source body, generate
any new render-model or PPTX export logic, call any external service,
or leave any artifact under the committed repo tree. The bundle, the
out-dir, and every subprocess artifact live under a single
``tempfile.TemporaryDirectory()`` that is removed when the smoke
returns.

Hard constraints (every constraint aborts the run with rc != 0):

  --self-test
    is the only mode the smoke exposes. The smoke has no production
    CLI surface today.

  bundle assembly
    bytes are the same ``_TINY_PNG_BYTES`` + ``_TINY_JPEG_BYTES`` the
    operator helper's --self-test uses. Filenames carry the
    ``mock_generated_`` prefix so the provenance trail is unmistakable
    in the produced summary.json (the operator helper preserves the
    operator filename verbatim under ``image_provenance[].
    operator_filename``).

  manifest content
    the safe-wording manifest names exactly the two mock-generated
    files in manifest-array order. Every slide_title / alt_text /
    intended_use value is hand-picked to pass every
    ``validate_operator_review_package.py`` string-safety scan
    (credential / URL / dangerous-URI-scheme / public-hosting /
    confidential / customer / raw-source / positive-real-service-claim /
    telemetry-emission), so a regression in either the operator helper
    OR the validator that started leaking dangerous wording would
    surface as a rc != 0 from the validator step.

  rc gates
    the operator helper must exit 0, the validator must exit 0, and
    ``summary.image_provenance`` must contain exactly two entries
    (one per mock-generated file) each ticking every provenance gate
    above. Anything else fails the smoke; the per-failure detail
    names the file + which gate tripped.

  repo immutability
    ``examples/`` and ``scripts/`` are snapshotted before and after
    the subprocess chain; any drift (the operator helper or validator
    accidentally writing under the committed tree) fails the smoke
    even when the chain itself returns 0. Mirrors the gate the
    operator helper's own --self-test applies.

Stdlib-only. The smoke shells out to the two existing entry points so
their argparse + fail-closed gates + stdout/stderr cascade are
exercised verbatim, no logic is duplicated.

Constraints honored: this smoke does NOT call D-One, MCP, Qoder, a
public network, a telemetry endpoint, a model API, an image search,
or any external service. It does NOT rebuild ``dist/`` or leave any
PPTX / zip / report artifact under the repo. It does NOT plan a deck
from any source body or implement broad prompt/report-to-PPTX
automation. Temp fixtures only.
"""
from __future__ import annotations

import sys

# Refuse to write `.pyc` files for any module imported by this smoke.
# The smoke's contract says it writes only under the tempdir; without
# this gate the first-party imports below would silently land
# ``scripts/__pycache__/*.pyc`` on a clean checkout, violating the
# no-generated-repo-artifacts contract. Must come BEFORE any first-
# party import — the interpreter checks the flag at bytecode-write
# time.
sys.dont_write_bytecode = True

import argparse  # noqa: E402
import json  # noqa: E402
import os  # noqa: E402
import subprocess  # noqa: E402
import tempfile  # noqa: E402
from dataclasses import dataclass  # noqa: E402
from pathlib import Path  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = REPO_ROOT / "scripts"

OPERATOR_HELPER = SCRIPTS_DIR / "operator_local_images_to_editable_ppt.py"
PACKAGE_VALIDATOR = SCRIPTS_DIR / "validate_operator_review_package.py"

# Minimum-viable magic-byte-valid PNG / JPEG payloads. Byte-distinct so
# sha256(PNG) != sha256(JPEG) and the per-image provenance attribution
# can prove "every mock-generated file embedded" honestly. Same bytes
# the operator helper's own --self-test uses (kept in sync via the
# constants block in ``operator_local_images_to_editable_ppt.py``);
# duplicated here so the smoke does not depend on importing a private
# constant from a 9k-line file just to read 30 bytes.
_TINY_PNG_BYTES: bytes = bytes.fromhex(
    "89504e470d0a1a0a"
    "0000000d49484452"
    "0000000100000001"
    "08060000001f15c489"
    "0000000d49444154"
    "789c6300010000000500010d0a2db4"
    "0000000049454e44ae426082"
)
_TINY_JPEG_BYTES: bytes = (
    b"\xff\xd8\xff\xe0"
    b"\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00"
    b"\xff\xd9"
)

# The two mock-generated filenames. The ``mock_generated_`` prefix
# distinguishes this lane's provenance from the operator-photo lane
# the same helper already supports — a future reader scanning the
# produced summary.json sees "operator_filename = mock_generated_*"
# and can attribute the bytes back to this smoke without digging
# through git history. Stems match the source_image_asset id pattern
# ``^[A-Za-z0-9][A-Za-z0-9_.\\-]*$`` the operator helper enforces.
_MOCK_ALPHA = "mock_generated_alpha.png"
_MOCK_BETA = "mock_generated_beta.jpg"


# ---------------------------------------------------------------------------
# Bundle assembly. The bundle layout matches the operator helper's
# --bundle shortcut contract exactly: <bundle>/images/<file>.png|jpg|jpeg
# (flat, non-symlink), plus optional <bundle>/manifest.json.
# ---------------------------------------------------------------------------


def _write_bundle(bundle: Path) -> None:
    """Materialize the bundle at ``bundle/``.

    Writes:
      <bundle>/images/mock_generated_alpha.png  (PNG bytes)
      <bundle>/images/mock_generated_beta.jpg   (JPEG bytes)
      <bundle>/manifest.json                    (safe per-image metadata)

    No symlinks, no subdirectories under images/, no manifest fields
    that would trip the validator's string-safety scans."""
    images = bundle / "images"
    images.mkdir(parents=True, exist_ok=False)
    (images / _MOCK_ALPHA).write_bytes(_TINY_PNG_BYTES)
    (images / _MOCK_BETA).write_bytes(_TINY_JPEG_BYTES)
    manifest = {
        "schema_version": "1",
        "images": [
            {
                "filename": _MOCK_ALPHA,
                "slide_title": "Mock generated alpha accent",
                "alt_text": "Mock generated alpha marker bytes",
                "intended_use": "decorative accent",
            },
            {
                "filename": _MOCK_BETA,
                "slide_title": "Mock generated beta accent",
                "alt_text": "Mock generated beta marker bytes",
                "intended_use": "decorative accent",
            },
        ],
    }
    (bundle / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# Subprocess invocation.
# ---------------------------------------------------------------------------


@dataclass
class _StageOutcome:
    name: str
    cmd: list[str]
    rc: int
    stdout: str
    stderr: str

    @property
    def ok(self) -> bool:
        return self.rc == 0


def _run(name: str, cmd: list[str]) -> _StageOutcome:
    env = {**os.environ, "PYTHONDONTWRITEBYTECODE": "1"}
    proc = subprocess.run(
        cmd, cwd=REPO_ROOT, capture_output=True, text=True, env=env,
    )
    return _StageOutcome(
        name=name, cmd=cmd, rc=proc.returncode,
        stdout=proc.stdout, stderr=proc.stderr,
    )


def _print_stage(stage: _StageOutcome) -> None:
    mark = "PASS" if stage.ok else "FAIL"
    print(f"  [{mark}] {stage.name} (rc={stage.rc})")
    if not stage.ok:
        for label, text in (
            ("stdout", stage.stdout), ("stderr", stage.stderr),
        ):
            tail = (text or "").splitlines()[-20:]
            if tail:
                print(f"    {label} tail:")
                for line in tail:
                    print(f"      {line}")


# ---------------------------------------------------------------------------
# Provenance assertions on the produced summary.json.
# ---------------------------------------------------------------------------


def _assert_provenance(summary: dict) -> tuple[bool, str]:
    """Assert ``summary.image_provenance`` ties each mock-generated file
    to ``ppt/media/*`` parts AND to embedding slides AND tags
    ``placement_verified=True``.

    Returns (ok, msg). On success msg is empty; on the first failure
    msg names the offending row + which gate tripped."""
    image_count = summary.get("image_count")
    if image_count != 2:
        return False, (
            f"summary.image_count={image_count!r}; expected 2 "
            f"(one mock-generated PNG + one mock-generated JPEG)."
        )
    prov = summary.get("image_provenance")
    if not isinstance(prov, list) or len(prov) != 2:
        n = len(prov) if isinstance(prov, list) else "n/a"
        return False, (
            f"summary.image_provenance length={n}; expected 2."
        )
    # Order-insensitive: both mock-generated filenames must appear,
    # each tying to its own provenance row. The bundle manifest pins
    # alpha first / beta second; the helper preserves manifest-array
    # order, but the smoke does not encode that ordering choice into
    # the assertion so a future bundle that reorders the manifest
    # does not false-fail.
    expected_filenames = {_MOCK_ALPHA, _MOCK_BETA}
    expected_titles = {
        _MOCK_ALPHA: "Mock generated alpha accent",
        _MOCK_BETA: "Mock generated beta accent",
    }
    seen_filenames: list[str] = []
    seen_parts: list[str] = []
    seen_slides: list[int] = []
    for i, entry in enumerate(prov):
        if not isinstance(entry, dict):
            return False, (
                f"image_provenance[{i}] is not a JSON object."
            )
        filename = entry.get("operator_filename")
        if filename not in expected_filenames:
            return False, (
                f"image_provenance[{i}].operator_filename="
                f"{filename!r}; expected one of "
                f"{sorted(expected_filenames)!r}."
            )
        if filename in seen_filenames:
            return False, (
                f"image_provenance[{i}].operator_filename="
                f"{filename!r} repeats; each mock-generated file "
                f"must appear in exactly one row."
            )
        seen_filenames.append(filename)
        parts = entry.get("embedded_media_parts")
        if not isinstance(parts, list) or not parts:
            return False, (
                f"image_provenance[{i}] for {filename!r} carries "
                f"embedded_media_parts={parts!r}; expected at least "
                f"one ppt/media/* part (the mock-generated bytes did "
                f"not embed)."
            )
        for j, part in enumerate(parts):
            if not isinstance(part, str) or not part.startswith(
                "ppt/media/"
            ):
                return False, (
                    f"image_provenance[{i}] for {filename!r} "
                    f"embedded_media_parts[{j}]={part!r}; expected "
                    f"a 'ppt/media/...' part path."
                )
            seen_parts.append(part)
        intended = entry.get("intended_slide_index")
        if not isinstance(intended, int) or intended < 1:
            return False, (
                f"image_provenance[{i}] for {filename!r} "
                f"intended_slide_index={intended!r}; expected a "
                f"positive int."
            )
        ref = entry.get("embedded_referencing_slides")
        if not isinstance(ref, list) or not ref:
            return False, (
                f"image_provenance[{i}] for {filename!r} "
                f"embedded_referencing_slides={ref!r}; expected the "
                f"sorted union of slides that <p:pic>-embed the "
                f"file's bytes."
            )
        if intended not in ref:
            return False, (
                f"image_provenance[{i}] for {filename!r} "
                f"intended_slide_index={intended} is missing from "
                f"embedded_referencing_slides={ref}; the mock-"
                f"generated bytes embedded at the wrong slide."
            )
        seen_slides.append(intended)
        if entry.get("placement_verified") is not True:
            return False, (
                f"image_provenance[{i}] for {filename!r} "
                f"placement_verified={entry.get('placement_verified')!r}; "
                f"expected True (intended_slide_index in "
                f"embedded_referencing_slides)."
            )
        # Operator manifest fields should flow through verbatim — the
        # bundle's manifest.json supplied them and the helper echoes
        # them onto each row when --manifest was resolved.
        expected_title = expected_titles[filename]
        if entry.get("operator_slide_title") != expected_title:
            return False, (
                f"image_provenance[{i}] for {filename!r} "
                f"operator_slide_title="
                f"{entry.get('operator_slide_title')!r}; expected "
                f"{expected_title!r} (bundle manifest verbatim)."
            )
    # Both mock-generated filenames must have appeared.
    if set(seen_filenames) != expected_filenames:
        missing = sorted(expected_filenames - set(seen_filenames))
        return False, (
            f"image_provenance does not name every mock-generated "
            f"file; missing {missing!r}."
        )
    # Distinct files must map to distinct media parts (sha256 differs
    # between the PNG and JPEG payloads above, so embedded_media_parts
    # must not collide row-to-row). Catches a regression where the
    # helper accidentally pointed both rows at the same media part.
    flat_parts: set[str] = set()
    for parts in (
        prov[0].get("embedded_media_parts", []),
        prov[1].get("embedded_media_parts", []),
    ):
        for part in parts:
            if part in flat_parts:
                return False, (
                    f"two mock-generated images share ppt/media/* "
                    f"part {part!r}; expected each row to map to a "
                    f"distinct part (byte-distinct payloads)."
                )
            flat_parts.add(part)
    return True, ""


# ---------------------------------------------------------------------------
# Repo-immutability snapshot.
# ---------------------------------------------------------------------------


def _snapshot_dir(d: Path) -> dict[str, bytes]:
    out: dict[str, bytes] = {}
    if not d.is_dir():
        return out
    for p in sorted(d.rglob("*")):
        if p.is_symlink() or not p.is_file():
            continue
        out[str(p.relative_to(d))] = p.read_bytes()
    return out


def _check_repo_unchanged(
    *, examples_before: dict[str, bytes],
    scripts_before: dict[str, bytes],
) -> tuple[bool, str]:
    examples_after = _snapshot_dir(REPO_ROOT / "examples")
    if examples_before != examples_after:
        changed = sorted(
            k for k in set(examples_before) | set(examples_after)
            if examples_before.get(k) != examples_after.get(k)
        )
        return False, (
            f"examples/ was mutated by the smoke (changed: {changed!r})"
        )
    scripts_after = _snapshot_dir(REPO_ROOT / "scripts")
    if scripts_before != scripts_after:
        changed = sorted(
            k for k in set(scripts_before) | set(scripts_after)
            if scripts_before.get(k) != scripts_after.get(k)
        )
        return False, (
            f"scripts/ was mutated by the smoke (changed: {changed!r})"
        )
    return True, ""


# ---------------------------------------------------------------------------
# Self-test driver.
# ---------------------------------------------------------------------------


def _run_self_test() -> int:
    print(
        "=== mock_generated_images_to_editable_ppt_smoke --self-test ==="
    )
    examples_before = _snapshot_dir(REPO_ROOT / "examples")
    scripts_before = _snapshot_dir(REPO_ROOT / "scripts")

    rc = 0
    with tempfile.TemporaryDirectory(
        prefix="mock-gen-img-handoff-",
    ) as raw_td:
        td = Path(raw_td)
        bundle = td / "bundle"
        out_dir = td / "out"
        _write_bundle(bundle)

        operator_stage = _run(
            "operator_local_images_to_editable_ppt --bundle",
            [
                sys.executable, str(OPERATOR_HELPER),
                "--bundle", str(bundle),
                "--out-dir", str(out_dir),
            ],
        )
        _print_stage(operator_stage)
        if not operator_stage.ok:
            print(
                "FAIL: the operator helper refused the mock-generated "
                "bundle; the handoff cannot proceed.",
                file=sys.stderr,
            )
            return 1

        validator_stage = _run(
            "validate_operator_review_package --out-dir",
            [
                sys.executable, str(PACKAGE_VALIDATOR),
                "--out-dir", str(out_dir),
            ],
        )
        _print_stage(validator_stage)
        if not validator_stage.ok:
            print(
                "FAIL: the review-package validator refused the "
                "mock-generated handoff's out-dir.",
                file=sys.stderr,
            )
            return 1

        summary_path = out_dir / "summary.json"
        try:
            summary = json.loads(summary_path.read_text())
        except (OSError, json.JSONDecodeError) as exc:
            print(
                f"FAIL: cannot read {summary_path}: "
                f"{type(exc).__name__}: {exc}",
                file=sys.stderr,
            )
            return 1
        ok, msg = _assert_provenance(summary)
        if ok:
            print("  [PASS] summary.image_provenance ties each mock-")
            print(
                "         generated filename to ppt/media parts and "
                "intended/readback slides"
            )
        else:
            print(f"  [FAIL] provenance: {msg}", file=sys.stderr)
            return 1

    ok, msg = _check_repo_unchanged(
        examples_before=examples_before,
        scripts_before=scripts_before,
    )
    if ok:
        print(
            "  [PASS] no committed repo path under examples/ or "
            "scripts/ was mutated"
        )
    else:
        print(f"  [FAIL] repo immutability: {msg}", file=sys.stderr)
        return 1

    print(
        "=== mock_generated_images_to_editable_ppt_smoke "
        "--self-test: 4 checks passed ==="
    )
    return rc


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Mock-generated PNG / JPEG image bytes -> editable-PPT "
            "operator review package handoff smoke. Drives "
            "operator_local_images_to_editable_ppt --bundle + "
            "validate_operator_review_package --out-dir under a single "
            "tempfile.TemporaryDirectory() and asserts "
            "summary.image_provenance ties each mock-generated filename "
            "to ppt/media parts and intended/readback slides. NOT a "
            "new runtime product. MOCK / STUB only — does NOT call "
            "D-One, MCP, Qoder, a public network, telemetry, a model "
            "API, image search, or any external service. Stdlib-only."
        ),
    )
    parser.add_argument(
        "--self-test", action="store_true",
        help=(
            "Run the handoff smoke under a single "
            "tempfile.TemporaryDirectory(). The smoke has no other "
            "mode today; --self-test is required."
        ),
    )
    args = parser.parse_args(argv)
    if not args.self_test:
        print(
            "FAIL: mock_generated_images_to_editable_ppt_smoke.py "
            "requires --self-test (no production CLI surface exists "
            "today).",
            file=sys.stderr,
        )
        return 2
    return _run_self_test()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
